version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/G-11-P/starport-installer"

[[analyzers]]
name = "ruby"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "rubocop"
enabled = true